---
- name: parted test
  hosts: servers
  tasks:
    - name: create primary partition
      parted:
        device: /dev/sdb
        number: 1
        part_end: 800MiB
        state: present

    - name: create vg
      lvg:
        vg: vg_database
        pvs: /dev/sdb1

    - name: create lv
      lvol:
        vg: vg_database
        lv: lv_mysql
        size: 512

    - name: create fs
      filesystem:
        fstype: xfs
        dev: /dev/vg_database/lv_mysql
      
