---
- name: Remove user
  hosts: test
  vars_files:
    - vars/users.yml
  tasks:
    - name: Remove group
      group:
        name: "{{ groupname }}"
        state: absent

    - name: Remove user
      user:
        name: "{{ username }}"
        state: absent
